export enum CategoriasProducto {
  ELECTRODOMESTICO = 'ELECTRODOMESTICO',
  INDUMENTARIA = 'INDUMENTARIA',
  ALIMENTICIO = 'ALIMENTICIO',
  MUEBLE = 'MUEBLE',
  FERRETERIA = 'FERRETERIA',
  ELECTRONICOS = 'ELECTRONICOS',
  BAZAR = 'BAZAR',
  JARDINERIA = 'JARDINERIA'
}